version: "3.8"
services:
  # The below temporal service definitions are borrowed from https://github.com/temporalio/docker-compose/blob/main/docker-compose.yml
  temporal-elasticsearch:
    container_name: tam-up_temporal-elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    # Version set on 2022-12-14 by Chandler
    image: elasticsearch:8.5.3
    # TODO(phoenix): networks
    networks:
      - temporal-network
    expose:
      - 9200
    volumes:
      - /var/lib/elasticsearch/data
  tam-up-db:
    container_name: tam-up_db
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: badpass
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:15
    networks:
      - temporal-network
    ports:
      - 65432:5432
    volumes:
      - ./state/local-tamup-db:/var/lib/postgresql/tamup-db
  temporal-postgresql:
    container_name: tam-up_temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    # Version set on 2022-12-14 by Chandler
    image: postgres:15
    networks:
      - temporal-network
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data
  temporal:
    container_name: tam-up_temporal
    depends_on:
      - temporal-postgresql
      - temporal-elasticsearch
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=true
      - ES_SEEDS=temporal-elasticsearch
      - ES_VERSION=v7
    image: temporalio/auto-setup:latest
    networks:
      - temporal-network
    ports:
      - 32104:7233
    labels:
      kompose.volume.type: configMap
    volumes:
      - ./local-temporal-dynamicconfig:/etc/temporal/config/dynamicconfig
  temporal-ui:
    container_name: tam-up_temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      # TODO(phoenix): what is this
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:latest
    networks:
      - temporal-network
    ports:
      - 32105:8080
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
